services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:4200"
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - net

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  db_data:
    driver: local